packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "esbuild"
  - "sharp"
  - "keccak"
  - "secp256k1"
  - "bufferutil"
  - "utf-8-validate"
